version: "3"

services:

  minio:
    image: minio/minio
    command: 'server --console-address ":9001" /data'
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
  minio_storage:
