version: "3"

services:

  minio:
    image: minio/minio
    command: 'server --console-address ":9001" /data'
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data

  postgres:
    image: postgres:15.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: threadr
      POSTGRES_PASSWORD: threadr
      POSTGRES_DB: threadr
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - redis:/data

volumes:
  pgdata:
  redis:
  minio_storage:
